# Practice pandas data manipulation

In [23]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#### 1. Load the Mad Men cast show data into a pandas DataFrame

In [2]:
cast_data = '../datasets/mad-men-cast-show-data.csv'

In [3]:
data = pd.read_csv('../datasets/mad-men-cast-show-data.csv')

#### 2. Print the head and tail of the data

In [4]:
data.head()
data.tail()

,Performer,Show,Show Start,Show End,Status?,CharEnd,Years Since,#LEAD,#SUPPORT,#Shows,Score,Score/Y,lead_notes,support_notes,show_notes
243,Meghan Wolfe,True Detective,2014,PRESENT,LEFT,2014,1,0,0,0,0.00,0,NaN,NaN,NaN
244,Kevin Dunn,True Detective,2014,PRESENT,LEFT,2014,1,0,1,2,2.25,2.25,NaN,"Draft Day, 2014","Veep, Season 3-4"
245,Charles Dance,Game of Thrones,2011,PRESENT,LEFT,2015,0,0,2,1,1.50,#DIV/0!,NaN,"Woman in Gold, 2015; Child 44, 2015","Deadline Gallipoli, Season 1"
246,Patrick Dempsey,Grey's Anatomy,2005,PRESENT,LEFT,2015,0,0,0,0,0.00,#DIV/0!,NaN,NaN,NaN
247,Ian McElhinney,Game of Thrones,2011,PRESENT,LEFT,2015,0,0,0,0,0.00,#DIV/0!,NaN,NaN,NaN

#### 3. Print the columns of the data

In [5]:
data.columns

Index([u'Performer', u'Show', u'Show Start', u'Show End', u'Status?',
       u'CharEnd', u'Years Since', u'#LEAD', u'#SUPPORT', u'#Shows', u'Score',
       u'Score/Y', u'lead_notes', u'support_notes', u'show_notes'],
      dtype='object')

#### 4. Rename any columns with spaces or special characters to not have them

In [35]:
data = data.rename(columns=lambda x: x.replace('?', ''))
data.columns

Index([u'Performer', u'Show', u'Show_Start', u'Show_End', u'Status',
       u'CharEnd', u'Years_Since', u'LEAD', u'SUPPORT', u'Shows', u'Score',
       u'Score/Y', u'lead_notes', u'support_notes', u'show_notes'],
      dtype='object')

AttributeError: 'DataFrame' object has no attribute 'Status'

#### 5. Subset the data where the status of the show is not "END" or "End"

In [36]:
subset = data[(data.Status!='END') & (data.Status!= 'End')]
subset

,Performer,Show,Show_Start,Show_End,Status,CharEnd,Years_Since,LEAD,SUPPORT,Shows,Score,Score/Y,lead_notes,support_notes,show_notes
157,Siobhan Finneran,Downton Abbey,2010,PRESENT,LEFT,2012,3,0,0,8,8.00,2.666666667,NaN,NaN,"The Syndicate, Season 2; Happy Valley, Season ..."
162,Eric Dane,Grey's Anatomy,2005,PRESENT,LEFT,2012,3,0,0,1,1.00,0.333333333,NaN,NaN,"The Last Ship, Season 1"
163,David Harewood,Homeland,2011,PRESENT,LEFT,2012,3,0,0,1,1.00,0.333333333,NaN,NaN,"Selfie, Season 1"
171,Dan Stevens,Downton Abbey,2010,PRESENT,LEFT,2012,3,3,4,0,4.00,1.333333333,"Summer in February, 2014; The Guest, 2014; Nig...","Vamps, 2012; The Fifth Estate, 2013; A Walk Am...",NaN
173,Michelle Fairley,Game of Thrones,2011,PRESENT,LEFT,2013,2,0,2,3,3.50,1.75,NaN,"Ironclad: Battle for Blood, 2014; Jack et la m...","Suits, Season 3; 24: Live Another Day, Season ..."
177,Morena Baccarin,Homeland,2011,PRESENT,LEFT,2013,2,1,0,2,3.00,1.5,"Back in the Day, 2014",NaN,"The Red Tent, Season 1; Gotham, Season 1"
178,Diego Klattenhoff,Homeland,2011,PRESENT,LEFT,2013,2,1,0,2,3.00,1.5,"Pacific Rim, 2013",NaN,"The Blacklist, Season 1-2"
179,Marg Helgenberger,CSI: Crime Scene Investigations,2000,PRESENT,LEFT,2013,2,0,0,1,1.00,0.5,NaN,NaN,"Intelligence, Season 1"
200,Jackson Pace,Homeland,2011,PRESENT,LEFT,2013,2,0,0,0,0.00,0,NaN,NaN,NaN
201,Morgan Saylor,Homeland,2011,PRESENT,LEFT,2013,2,0,2,0,0.50,0.25,NaN,"Jamie Marks is Dead, 2014; McFarland, USA, 2015",NaN
205,Rory McCann,Game of Thrones,2011,PRESENT,LEFT,2014,1,0,0,1,1.00,1,NaN,NaN,"Banished, Season 1"
208,Paul Guilfoyle,CSI: Crime Scene Investigations,2000,PRESENT,LEFT,2014,1,0,0,0,0.00,0,NaN,NaN,NaN
231,Jack Gleeson,Game of Thrones,2011,PRESENT,LEFT,2014,1,0,0,0,0.00,0,NaN,NaN,NaN
232,Michael Gill,House of Cards,2013,PRESENT,LEFT,2014,1,0,0,0,0.00,0,NaN,NaN,NaN
233,Matthew McConaughey,True Detective,2014,PRESENT,LEFT,2014,1,1,0,0,1.00,1,"Interstellar, 2014",NaN,NaN
234,Woody Harrelson,True Detective,2014,PRESENT,LEFT,2014,1,0,2,0,0.50,0.5,NaN,"The Hunger Games: Mockingjay - Part 1, 2014; T...",NaN
235,Michelle Monaghan,True Detective,2014,PRESENT,LEFT,2014,1,4,0,0,4.00,4,"Better Living through Chemistry, 2014; Fort Bl...",NaN,NaN
236,Michael Potts,True Detective,2014,PRESENT,LEFT,2014,1,0,0,0,0.00,0,NaN,NaN,NaN
237,Dana Gourrier,True Detective,2014,PRESENT,LEFT,2014,1,0,0,0,0.00,0,NaN,NaN,NaN
238,Michael Irby,True Detective,2014,PRESENT,LEFT,2014,1,0,0,0,0.00,0,NaN,NaN,NaN
239,Joe Chrest,True Detective,2014,PRESENT,LEFT,2014,1,0,1,0,0.25,0.25,NaN,"Black or White, 2015",NaN
240,Dane Rhodes,True Detective,2014,PRESENT,LEFT,2014,1,0,1,0,0.25,0.25,NaN,"When the Game Stands Tall, 2014",NaN
241,Michael Hyatt,True Detective,2014,PRESENT,LEFT,2014,1,0,1,0,0.25,0.25,NaN,"Nightcrawler, 2014",NaN
242,Tony Molina Jr.,True Detective,2014,PRESENT,LEFT,2014,1,0,0,0,0.00,0,NaN,NaN,NaN
243,Meghan Wolfe,True Detective,2014,PRESENT,LEFT,2014,1,0,0,0,0.00,0,NaN,NaN,NaN
244,Kevin Dunn,True Detective,2014,PRESENT,LEFT,2014,1,0,1,2,2.25,2.25,NaN,"Draft Day, 2014","Veep, Season 3-4"
245,Charles Dance,Game of Thrones,2011,PRESENT,LEFT,2015,0,0,2,1,1.50,#DIV/0!,NaN,"Woman in Gold, 2015; Child 44, 2015","Deadline Gallipoli, Season 1"
246,Patrick Dempsey,Grey's Anatomy,2005,PRESENT,LEFT,2015,0,0,0,0,0.00,#DIV/0!,NaN,NaN,NaN
247,Ian McElhinney,Game of Thrones,2011,PRESENT,LEFT,2015,0,0,0,0,0.00,#DIV/0!,NaN,NaN,NaN

#### 6. Print out the performers where the show start is greater than 2005 and the score is greater than 7.

In [37]:
data[(data.Show_Start > 2005) & (data.Score > 7)]
print data.Performers

AttributeError: 'DataFrame' object has no attribute 'Performers'

#### 7. Select the performer and show column for the 20th thru 25th LABELED row.

In [22]:
data.ix[20:26, ['Performer', 'Show']]

             Performer             Show
20    Mary Steenburgen  Joan of Arcadia
21  Mathew St. Patrick   Six Feet Under
22       Michael Welch  Joan of Arcadia
23    Aaron Himelstein  Joan of Arcadia
24     Becky Wahlstrom  Joan of Arcadia
25     Chris Marquette  Joan of Arcadia
26       Mageina Tovah  Joan of Arcadia

#### 8. Plot a histogram of score

In [38]:
plt.hist(cast_data['Score'])

TypeError: string indices must be integers, not str